name: Node.js CI

on:
    push:
        branches:
            - '*'

jobs:
    ci-workflows:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Format code with Prettier
              run: npm run format

            - name: Check for formatting changes
              run: git diff --exit-code
