name: Node.js CI

on:
    push:
        branches:
            - '*'

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci

    run-tests:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v2
            - name: Run tests with coverage
              run: npm test

    save-coverage-report:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - uses: actions/checkout@v2
            - name: Save coverage report
              uses: actions/upload-artifact@v2
              with:
                  name: coverage-report
                  path: coverage/coverage-report.html

    format-code:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - uses: actions/checkout@v2
            - name: Format code with Prettier
              run: npm run format

    check-formatting:
        runs-on: ubuntu-latest
        needs: format-code
        steps:
            - uses: actions/checkout@v2
            - name: Check for formatting changes
              run: git diff --exit-code || exit 1
